/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package open.data.structure.kt

class App {
    val greeting: String
        get() {
            return "Hello world!!!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
